
services:
  minecraft:
    image: docker.io/itzg/minecraft-server:stable-java21
    container_name: minecraft-server
    restart: unless-stopped
    userns_mode: keep-id
    # user: "${PUID:-1000}:${PGID:-1000}"
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "25575:25575/tcp"
      - "8787:8787/tcp"
    environment:
      EULA: "TRUE"
      ENABLE_QUERY: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: 20e49c761220cbeb1947a29d
      RCON_PORT: "25575"
      MINECRAFT_RCON_ALLOWLIST: list,whitelist,op,deop,ban,pardon,banlist,kick,say,save-all,stop,tps
      CF_API_KEY: "$$2a$10$$CGIKTrCo9bFiCKwScOL.o.SUVdrawTyYwLEcF72CxmXxNF.tYPuvu"
      # TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.4.10"
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_MODPACK_MANIFEST: /manifests/manifest.json
      CF_MODPACK_ZIP: /downloads/GodsChildren-1.5.0.zip
      CF_SLUG: godschildren
      CF_EXCLUDE_MODS: "even-more-origins-keybinds"
    volumes:
      - ../minecraft-data:/data
      - ../downloads:/downloads
